# .github/dependabot.yml
version: 2
updates:
  # Enable version updates for npm packages
  - package-ecosystem: 'npm'
    directory: '/' # Location of package.json
    schedule:
      interval: 'weekly' # How often to check for updates
    commit-message:
      prefix: 'chore(deps)' # Conventional commit prefix for dependency updates
    # Target the 'main' branch for PRs
    target-branch: 'main'
    groups:
      devDependencies:
        dependency-type: 'development'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/' # Location of your .github/workflows directory
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(ci)' # Conventional commit prefix for CI updates
    # Target the 'main' branch for PRs
    target-branch: 'main'
